In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from tqdm import tqdm, tqdm_notebook

In [35]:
df = pd.read_csv('full_podaci.csv')

In [36]:
df.head()

,url,naziv,cijena,lokacija,lat lng
0,https://www.olx.ba/artikal/31090915/trosoban-s...,"Trosoban stan,82m2 Čengić Vila RENOVIRAN",178.900 KM,Novo Sarajevo,"https://maps.google.com/maps?ll=43.850312,18.3..."
1,https://www.olx.ba/artikal/30412030/novogradnj...,NOVOGRADNJA/Otoka/stanovi/54-118m2/Sarajevo,2.250 KM,Novo Sarajevo,"https://maps.google.com/maps?ll=43.848706,18.3..."
2,https://www.olx.ba/artikal/31109536/bauland-pr...,BAULAND prodaje: Trosoban/ Novogradnja/Pejton,163.000 KM,Ilidža,"https://maps.google.com/maps?ll=43.833914,18.2..."
3,https://www.olx.ba/artikal/29115595/prostor-pr...,PROSTOR prodaje: NOVOGRADNJA trosoban stan sa ...,103.350 KM,"Sarajevo, Novi Grad","https://maps.google.com/maps?ll=43.850438,18.3..."
4,https://www.olx.ba/artikal/30908536/novogradnj...,"NOVOGRADNJA Skenderija, dvoiposoban 52-53m2 AK...",182.385 KM,Sarajevo - Centar,"https://maps.google.com/maps?ll=43.852924,18.4..."

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2409 entries, 0 to 2408
Data columns (total 5 columns):
url         2409 non-null object
naziv       2406 non-null object
cijena      2409 non-null object
lokacija    2409 non-null object
lat lng     2356 non-null object
dtypes: object(5)
memory usage: 94.2+ KB

In [38]:
df['lat lng'][0]

'https://maps.google.com/maps?ll=43.850312,18.369865&z=16&hl=en-US&gl=US&mapclient=apiv3'

In [39]:
# za latitude i longitude
coord = []
def cleaning(strings):
    for string in tqdm_notebook(strings):
        try:        
            x, y = (string.split('=')[1]).split(',')
            x = float(x)
            y = y.split('&')[0]
            coord_turn = (x,y)
            coord.append(coord_turn)
        except:
            coord_turn = ('NaN', 'NaN')
            coord.append(coord_turn)

In [40]:
extra = pd.DataFrame(df['lat lng'])
extra.apply(cleaning)

HBox(children=(IntProgress(value=0, max=2409), HTML(value='')))

lat lng    None
dtype: object

In [41]:
df1 = pd.DataFrame(coord, columns=['lat', 'lng'])
df1.head()

       lat        lng
0  43.8503  18.369865
1  43.8487  18.359522
2  43.8339   18.29901
3  43.8504   18.35629
4  43.8529  18.410201

In [42]:
df = df.join(df1, lsuffix='_df', rsuffix='_df1')

In [43]:
df.head()

,url,naziv,cijena,lokacija,lat lng,lat,lng
0,https://www.olx.ba/artikal/31090915/trosoban-s...,"Trosoban stan,82m2 Čengić Vila RENOVIRAN",178.900 KM,Novo Sarajevo,"https://maps.google.com/maps?ll=43.850312,18.3...",43.8503,18.369865
1,https://www.olx.ba/artikal/30412030/novogradnj...,NOVOGRADNJA/Otoka/stanovi/54-118m2/Sarajevo,2.250 KM,Novo Sarajevo,"https://maps.google.com/maps?ll=43.848706,18.3...",43.8487,18.359522
2,https://www.olx.ba/artikal/31109536/bauland-pr...,BAULAND prodaje: Trosoban/ Novogradnja/Pejton,163.000 KM,Ilidža,"https://maps.google.com/maps?ll=43.833914,18.2...",43.8339,18.29901
3,https://www.olx.ba/artikal/29115595/prostor-pr...,PROSTOR prodaje: NOVOGRADNJA trosoban stan sa ...,103.350 KM,"Sarajevo, Novi Grad","https://maps.google.com/maps?ll=43.850438,18.3...",43.8504,18.35629
4,https://www.olx.ba/artikal/30908536/novogradnj...,"NOVOGRADNJA Skenderija, dvoiposoban 52-53m2 AK...",182.385 KM,Sarajevo - Centar,"https://maps.google.com/maps?ll=43.852924,18.4...",43.8529,18.410201

In [44]:
df = df.drop('lat lng', axis =1)

In [45]:
df.head()

,url,naziv,cijena,lokacija,lat,lng
0,https://www.olx.ba/artikal/31090915/trosoban-s...,"Trosoban stan,82m2 Čengić Vila RENOVIRAN",178.900 KM,Novo Sarajevo,43.8503,18.369865
1,https://www.olx.ba/artikal/30412030/novogradnj...,NOVOGRADNJA/Otoka/stanovi/54-118m2/Sarajevo,2.250 KM,Novo Sarajevo,43.8487,18.359522
2,https://www.olx.ba/artikal/31109536/bauland-pr...,BAULAND prodaje: Trosoban/ Novogradnja/Pejton,163.000 KM,Ilidža,43.8339,18.29901
3,https://www.olx.ba/artikal/29115595/prostor-pr...,PROSTOR prodaje: NOVOGRADNJA trosoban stan sa ...,103.350 KM,"Sarajevo, Novi Grad",43.8504,18.35629
4,https://www.olx.ba/artikal/30908536/novogradnj...,"NOVOGRADNJA Skenderija, dvoiposoban 52-53m2 AK...",182.385 KM,Sarajevo - Centar,43.8529,18.410201

In [46]:
kolone = ['Kvadrata',
 'Broj soba','Adresa',
 'Godina izgradnje','Primarna orjentacija']

In [47]:
import requests
from bs4 import BeautifulSoup

In [48]:
linkovi = df['url']
linkovi = pd.DataFrame(linkovi)
linkovi.head()

                                                 url
0  https://www.olx.ba/artikal/31090915/trosoban-s...
1  https://www.olx.ba/artikal/30412030/novogradnj...
2  https://www.olx.ba/artikal/31109536/bauland-pr...
3  https://www.olx.ba/artikal/29115595/prostor-pr...
4  https://www.olx.ba/artikal/30908536/novogradnj...

In [49]:
# za dodatne podatke o stanovima(kvadratura, opca lokacija, adresa)

features_dict = {}
col = []
val = []
for i in tqdm_notebook(range(len(linkovi))):
    val_turn = []
    resp = requests.get(linkovi['url'][i])
    if str(resp) == '<Response [404]>':
        val.append('NaN')
    
    soup = BeautifulSoup(resp.text, 'html.parser')
    try:
        section1 = soup.find('div', id='dodatnapolja1')

        sections = section1.select('.df')
        for section in sections:
            x = section.select('.df1')[0].text.strip()
            y = section.select('.df2')[0].text.strip()
           
            if x in kolone:
                col.append(x)
                if y=='':
                    y='NaN'
                val_turn.append(y)            
                  
                
    except:
        val.append('NaN')
        continue
    
    val.append(val_turn)

HBox(children=(IntProgress(value=0, max=2409), HTML(value='')))

KeyboardInterrupt:

In [20]:
val2 = []

In [21]:
for i in val:
    if i == 'NaN':
        val2.append(['NaN'])
    else:
        val2.append(i)

In [22]:
val2 = pd.DataFrame(val2, columns=kolone)

In [24]:
val2.head()

,Kvadrata,Broj soba,Adresa,Godina izgradnje,Primarna orjentacija
0,73,Trosoban (3),Džemala Bijedića,1980-1989,None
1,54-118,Trosoban (3),None,None,None
2,67,Trosoban (3),Prve samostalne brigade,2010+,None
3,53,Trosoban (3),Džemala Bijedića,Novogradnja,Istok
4,52,Trosoban (3),Terezija,Novogradnja,None

In [25]:
df = df.join(val2, lsuffix='_df', rsuffix='_df2')

In [26]:
df.head()

,url,naziv,cijena,lokacija,lat,lng,Kvadrata,Broj soba,Adresa,Godina izgradnje,Primarna orjentacija
0,https://www.olx.ba/artikal/31090915/trosoban-s...,"Trosoban stan,82m2 Čengić Vila RENOVIRAN",178.900 KM,Novo Sarajevo,43.8503,18.369865,73,Trosoban (3),Džemala Bijedića,1980-1989,None
1,https://www.olx.ba/artikal/30412030/novogradnj...,NOVOGRADNJA/Otoka/stanovi/54-118m2/Sarajevo,2.250 KM,Novo Sarajevo,43.8487,18.359522,54-118,Trosoban (3),None,None,None
2,https://www.olx.ba/artikal/31109536/bauland-pr...,BAULAND prodaje: Trosoban/ Novogradnja/Pejton,163.000 KM,Ilidža,43.8339,18.29901,67,Trosoban (3),Prve samostalne brigade,2010+,None
3,https://www.olx.ba/artikal/29115595/prostor-pr...,PROSTOR prodaje: NOVOGRADNJA trosoban stan sa ...,103.350 KM,"Sarajevo, Novi Grad",43.8504,18.35629,53,Trosoban (3),Džemala Bijedića,Novogradnja,Istok
4,https://www.olx.ba/artikal/30908536/novogradnj...,"NOVOGRADNJA Skenderija, dvoiposoban 52-53m2 AK...",182.385 KM,Sarajevo - Centar,43.8529,18.410201,52,Trosoban (3),Terezija,Novogradnja,None

In [27]:
df.to_csv('stanovi_podaci_2018.csv', encoding='utf-8', index=False)

In [28]:
df = pd.read_csv('stanovi_podaci_2018.csv')

In [30]:
df['Kvadrata'].unique()

array(['73', '54-118', '67', '53', '52', '62', '81', '160', '40', '71',
       '63', '80', '64', '51.5', '105', '102,46', '65', '85', '88',
       '48,31', '29', '38', '65,85', '51,33', '68', '59', '55', '50',
       '69', '79', '83m2', '103', '125', '89', '66', '50,50', '95', '92',
       '82', '51,19', '46', '47', '60', '138', '98', '94', '57', '70',
       '56', '78', '58', '57,5', '39', '96', '69,61', '54', '146',
       '62,69m2', '74,68m2', '73,54', '52 m2', '97.5', '87', '48', '74',
       '113', '44', '62 m2', '53m2', '45', '32-70', '133', '84', '72',
       '80m2', '119', '46,77', '61', '52,5 m2', '49', '193', '44,50',
       '176', '102', '81,53', '142', '42', '93', '88,45 m2', '129', '34',
       '54m2', '104', '77', '31', '36 + 6', '57m2', '151', '20', '32',
       '33', '39,5', '62m2', '99', '60,5m2', '100 m2', '44m2', '100',
       '70m2', '69,5 M2', '90 m2', '56 m2', '86m2', '70 m2 + 30m2 tavan',
       '54 m2', '58m2', '89m2', '49M2', '68,7M2', '75 m2', '63m2', '74M2',
       '38,7m2', '88m2', '79m2', '81 m2', '63,5m2', '73m2', '30m2',
       '78 m2', '43m2', '43 m2', '68M2', '66m2', '55m2', '38m2', '49m2',
       '65m2', '26m2', '116m2', 'Od 80m2 ,do 90 m2', '41,72m2', '20m2',
       '59m2', '100m2', '135m2', '31m2', '56m2', '66 m2', '84 m2',
       '50 m2', '48,6m2', '75m2', '68 m2', '71m2', '34m2', '95 m2',
       '86M2', '101', '98 (116)', '107', '76', '75', '52( 48zk)', '167',
       '112', '28+2', '56,30', '111', '150', '55.3', '86', '115', '48m2',
       '41', '72m2', '90', '57m2 - 105,8m2', '121', '106', '108', '51',
       '85,67', nan, '83 / 92', '41,09', '70 + 3', '83', '120', '118',
       '110', '154', '63.5', '116', '170', '43', '77,67', '84m2', '41,24',
       '78.4', '92,75', '77,5', '65 m2', '71,90 m2', '72,94m2', '43,18m2',
       '79,18m2', '73,71m2', '72,96m2', '25', '69.4', '60,50', '55,30',
       '93, 64', '63,22', '122', '81,77', '114', '37', '84,34', '43 + 21',
       '68m2', '70 m2', '50,5', '80 + balkon', '55,3', '74 m2', '124',
       '140', '110 +10', '101 + 24', '61+9', '142.9', '134', '91', '86,5',
       '35', '131', '128', '130', '109', '136', '64m2', '126',
       '64,50 (129)', '137', '41 (85) m2', '93 (95)', '50,81', '73(90)',
       '38(62)', '53(83)', '112,83', '57(64)', '79,76', '42 m2', '84,45',
       '110(120)', '702', '45(73)', '77,50', '60 (100)', '39,41', '38,56',
       '28', '149,90', '91,45', '80,63', '30', '76m2', '40m2', '94m2',
       '73,85', '135', '200', '148', '147', '61m2', '157', '66,5', '97',
       '36m2', '209', '104+12', '32-110m2', '360', '36', '85m2', '77m2',
       '60m2', '67,50m2', '116,50', '42,65', '82,5', '68(104)', '94,5',
       '83.4', '93.9', '132', '54 +balkon', '156m2', '69m2', '48 + 4.5',
       '127 m2 + 18 m2', '78 + 2 + 3', '41.78 m2', '79,35',
       'Trosoban (3)', '50,28 m2', '162', '117,6', '72zk 75', '143',
       '68,57', '117,78', '96,22', '83,59', '97,39', '116,61', '115,16',
       '82 po papirima u stvarnosti preko 100',
       '37 m2 + balkon (ustakljen)', '24', '69,5', '92,20', '223',
       '122(130)', '364', '74,18', '56,00', '73,81', '73,37', '56,18',
       '73,21', '54,61', '90+48+16+15', 'od 41 m2 do 108 m2', '51,44',
       '73,02', '30 - 135', '88m2+ terasa', '27', '72.8', '118.3', '72.9',
       '72.5', '72.1', '76.4', '47m2', '50m2', '60,58m2', '74,36m2',
       '78m2 + balkon 6m2+podrumska ostava 5m2', '129m2', '60m', '71.3',
       '500m2', '78m2', '110,46', '52m2', '145', '44,5', '45,27',
       '130 m2', '113.5', '94.2', '66.6', '85m2(105m2)', '63,35',
       '63 + 4', '73 (85)', '60 m2', '104 m2', '230', '61.6', '61.5',
       '67m2', '66.5', '23', '33m2', '70m2 i 30m2', '86 +10 balkoni',
       '106,75', '74m2  SA 2 BALKONA KOJI NISU URACUNATI U KVADRATURU',
       '71,61', '6', '26', '215', '61,29', '59+6', '35,50m2', '139',
       '97,31', '80,02', '47,31', '113,14', '119 m2 (u knjigama 96 m2)',
       '100 (zk 62)', '98 m2', '67 m2', '106 m2', '58,50', '48,00',
       '63 m2', '110,14', '103m2', '18.do 24m2', '52,4', '37m2', '114,40',
       '117', '38 izvorno - 44 nakon adaptacije', '70 Kvadrata',
       '50, 65m2 - 110, 18m2', '65,5', '154 m2', '59+10(hobi soba)',
       '55-114', '45,26', '82+balkon', '29 + 17', '39m2', '82 m2', '190',
       '106m2(4m2)+16m2(urbanistička za balkon)', 'OD 80 DO 137', '57 m2',
       '54,31', '123', '86 bez dva balkona', '55m2 +16m2',
       '55 m2 + mogućnost proširenja 10 m2', '54m2  + 13,5 m2 gar',
       '56M2', '58 + 28', '96-100m2', '78,76', '57,29', '64 m2', '161',
       '81,68', '1300m2', '79 m2', '65 m2 + vlastita bašta', '45m2',
       '57.74 m2', '57,90', '75-130', '44,18', '56,43m2', '64,2', '174',
       '300', '62 + 2 balkona', '90m2', '54,6', '53-65m2', '180', '63,98',
       '134,46', '89,06', '41,70', '61,5', '29-180', '64 + 64', '174 m2'],
      dtype=object)

In [31]:
for i in range(len(df['Kvadrata'])):
    try:
        if 'm' in df['Kvadrata'][i]:
            df['Kvadrata'][i] = df['Kvadrata'][i].replace(df['Kvadrata'][i], df['Kvadrata'][i].split('m')[0])
    except:
        continue

c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [32]:
df['Kvadrata'].unique()

array(['73', '54-118', '67', '53', '52', '62', '81', '160', '40', '71',
       '63', '80', '64', '51.5', '105', '102,46', '65', '85', '88',
       '48,31', '29', '38', '65,85', '51,33', '68', '59', '55', '50',
       '69', '79', '83', '103', '125', '89', '66', '50,50', '95', '92',
       '82', '51,19', '46', '47', '60', '138', '98', '94', '57', '70',
       '56', '78', '58', '57,5', '39', '96', '69,61', '54', '146',
       '62,69', '74,68', '73,54', '52 ', '97.5', '87', '48', '74', '113',
       '44', '62 ', '45', '32-70', '133', '84', '72', '119', '46,77',
       '61', '52,5 ', '49', '193', '44,50', '176', '102', '81,53', '142',
       '42', '93', '88,45 ', '129', '34', '104', '77', '31', '36 + 6',
       '151', '20', '32', '33', '39,5', '99', '60,5', '100 ', '100',
       '69,5 M2', '90 ', '56 ', '86', '70 ', '54 ', '49M2', '68,7M2',
       '75 ', '74M2', '38,7', '81 ', '63,5', '30', '78 ', '43', '43 ',
       '68M2', '26', '116', 'Od 80', '41,72', '135', '66 ', '84 ', '50 ',
       '48,6', '75', '68 ', '95 ', '86M2', '101', '98 (116)', '107', '76',
       '52( 48zk)', '167', '112', '28+2', '56,30', '111', '150', '55.3',
       '115', '41', '90', '121', '106', '108', '51', '85,67', nan,
       '83 / 92', '41,09', '70 + 3', '120', '118', '110', '154', '63.5',
       '170', '77,67', '41,24', '78.4', '92,75', '77,5', '65 ', '71,90 ',
       '72,94', '43,18', '79,18', '73,71', '72,96', '25', '69.4', '60,50',
       '55,30', '93, 64', '63,22', '122', '81,77', '114', '37', '84,34',
       '43 + 21', '50,5', '80 + balkon', '55,3', '74 ', '124', '140',
       '110 +10', '101 + 24', '61+9', '142.9', '134', '91', '86,5', '35',
       '131', '128', '130', '109', '136', '126', '64,50 (129)', '137',
       '41 (85) ', '93 (95)', '50,81', '73(90)', '38(62)', '53(83)',
       '112,83', '57(64)', '79,76', '42 ', '84,45', '110(120)', '702',
       '45(73)', '77,50', '60 (100)', '39,41', '38,56', '28', '149,90',
       '91,45', '80,63', '73,85', '200', '148', '147', '157', '66,5',
       '97', '36', '209', '104+12', '32-110', '360', '67,50', '116,50',
       '42,65', '82,5', '68(104)', '94,5', '83.4', '93.9', '132',
       '54 +balkon', '156', '48 + 4.5', '127 ', '78 + 2 + 3', '41.78 ',
       '79,35', 'Trosoban (3)', '50,28 ', '162', '117,6', '72zk 75',
       '143', '68,57', '117,78', '96,22', '83,59', '97,39', '116,61',
       '115,16', '82 po papiri', '37 ', '24', '69,5', '92,20', '223',
       '122(130)', '364', '74,18', '56,00', '73,81', '73,37', '56,18',
       '73,21', '54,61', '90+48+16+15', 'od 41 ', '51,44', '73,02',
       '30 - 135', '27', '72.8', '118.3', '72.9', '72.5', '72.1', '76.4',
       '60,58', '74,36', '71.3', '500', '110,46', '145', '44,5', '45,27',
       '130 ', '113.5', '94.2', '66.6', '63,35', '63 + 4', '73 (85)',
       '60 ', '104 ', '230', '61.6', '61.5', '66.5', '23',
       '86 +10 balkoni', '106,75', '71,61', '6', '215', '61,29', '59+6',
       '35,50', '139', '97,31', '80,02', '47,31', '113,14', '119 ',
       '100 (zk 62)', '98 ', '67 ', '106 ', '58,50', '48,00', '63 ',
       '110,14', '18.do 24', '52,4', '114,40', '117',
       '38 izvorno - 44 nakon adaptacije', '70 Kvadrata', '50, 65',
       '65,5', '154 ', '59+10(hobi soba)', '55-114', '45,26', '82+balkon',
       '29 + 17', '82 ', '190', 'OD 80 DO 137', '57 ', '54,31', '123',
       '86 bez dva balkona', '55 ', '56M2', '58 + 28', '96-100', '78,76',
       '57,29', '64 ', '161', '81,68', '1300', '79 ', '57.74 ', '57,90',
       '75-130', '44,18', '56,43', '64,2', '174', '300', '62 + 2 balkona',
       '54,6', '53-65', '180', '63,98', '134,46', '89,06', '41,70',
       '61,5', '29-180', '64 + 64', '174 '], dtype=object)

In [34]:
df.to_csv('stanovi_podaci_2018.csv', encoding='utf-8', index=False)

In [64]:
df = pd.read_csv('stanovi_podaci_2018.csv')

In [90]:
df.head()

,url,naziv,cijena,lokacija,lat,lng,Kvadrata,Broj soba,Adresa,Godina izgradnje,Primarna orjentacija,status
0,https://www.olx.ba/artikal/31090915/trosoban-s...,"Trosoban stan,82m2 Čengić Vila RENOVIRAN",178.900 KM,Novo Sarajevo,43.850312,18.369865,73,Trosoban (3),Džemala Bijedića,1980-1989,NaN,None
1,https://www.olx.ba/artikal/30412030/novogradnj...,NOVOGRADNJA/Otoka/stanovi/54-118m2/Sarajevo,2.250 KM,Novo Sarajevo,43.848706,18.359522,54-118,Trosoban (3),NaN,NaN,NaN,novogradnja
2,https://www.olx.ba/artikal/31109536/bauland-pr...,BAULAND prodaje: Trosoban/ Novogradnja/Pejton,163.000 KM,Ilidža,43.833914,18.299010,67,Trosoban (3),Prve samostalne brigade,2010+,NaN,novogradnja
3,https://www.olx.ba/artikal/29115595/prostor-pr...,PROSTOR prodaje: NOVOGRADNJA trosoban stan sa ...,103.350 KM,"Sarajevo, Novi Grad",43.850438,18.356290,53,Trosoban (3),Džemala Bijedića,Novogradnja,Istok,novogradnja
4,https://www.olx.ba/artikal/30908536/novogradnj...,"NOVOGRADNJA Skenderija, dvoiposoban 52-53m2 AK...",182.385 KM,Sarajevo - Centar,43.852924,18.410201,52,Trosoban (3),Terezija,Novogradnja,NaN,novogradnja

In [169]:
df['status'] = 'nepoznat'

In [170]:
for i in df['naziv']:
    if  'novogradnja' in str(i).lower():
        df.loc[df['naziv'] == i, 'status'] = 'novogradnja'

In [91]:
df.head()

,url,naziv,cijena,lokacija,lat,lng,Kvadrata,Broj soba,Adresa,Godina izgradnje,Primarna orjentacija,status
0,https://www.olx.ba/artikal/31090915/trosoban-s...,"Trosoban stan,82m2 Čengić Vila RENOVIRAN",178.900 KM,Novo Sarajevo,43.850312,18.369865,73,Trosoban (3),Džemala Bijedića,1980-1989,NaN,None
1,https://www.olx.ba/artikal/30412030/novogradnj...,NOVOGRADNJA/Otoka/stanovi/54-118m2/Sarajevo,2.250 KM,Novo Sarajevo,43.848706,18.359522,54-118,Trosoban (3),NaN,NaN,NaN,novogradnja
2,https://www.olx.ba/artikal/31109536/bauland-pr...,BAULAND prodaje: Trosoban/ Novogradnja/Pejton,163.000 KM,Ilidža,43.833914,18.299010,67,Trosoban (3),Prve samostalne brigade,2010+,NaN,novogradnja
3,https://www.olx.ba/artikal/29115595/prostor-pr...,PROSTOR prodaje: NOVOGRADNJA trosoban stan sa ...,103.350 KM,"Sarajevo, Novi Grad",43.850438,18.356290,53,Trosoban (3),Džemala Bijedića,Novogradnja,Istok,novogradnja
4,https://www.olx.ba/artikal/30908536/novogradnj...,"NOVOGRADNJA Skenderija, dvoiposoban 52-53m2 AK...",182.385 KM,Sarajevo - Centar,43.852924,18.410201,52,Trosoban (3),Terezija,Novogradnja,NaN,novogradnja

In [171]:
for i in df['naziv']:
    if  'adaptiran' in str(i).lower():
        df.loc[df['naziv'] == i, 'status'] = 'renoviran'

In [172]:
for i in df['naziv']:
    if  'adaptiran' in str(i).lower():
        df.loc[df['naziv'] == i, 'status'] = 'adaptiran'

In [224]:
df['namjesten'] = 'no info'

In [225]:
for i in df['naziv']:
    if  'namjeste' in str(i).lower():
        df.loc[df['naziv'] == i, 'namjesten'] = 'DA'

In [173]:
df['balkon'] = 'NE'
for i in df['naziv']:
    if  'balkon' in str(i).lower():
        df.loc[df['naziv']==i, 'balkon'] = 'DA'

In [119]:
df['Godina izgradnje'].value_counts()

1980-1989      267
Novogradnja    256
1970-1979      142
2010+          110
Prije 1950     103
2000-2009      101
1960-1969       75
1990-1999       49
2015+           32
1950-1959       26
Ostalo          14
Name: Godina izgradnje, dtype: int64

In [144]:
for i in df['Kvadrata']:
    if  'balkon' in str(i).lower():
        df.loc[df['Kvadrata']==i, 'balkon'] = 'DA'

In [178]:
for i in df['naziv']:
    if  'opremlj' in str(i).lower():
        df.loc[df['naziv'] == i, 'namjesten'] = 'DA'

In [197]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2405 entries, 0 to 2404
Data columns (total 14 columns):
url                     2405 non-null object
naziv                   2402 non-null object
cijena                  2405 non-null int64
lokacija                2405 non-null object
lat                     2352 non-null float64
lng                     2352 non-null float64
Kvadrata                2402 non-null object
Broj soba               2402 non-null object
Adresa                  2232 non-null object
Godina izgradnje        1175 non-null object
Primarna orjentacija    1028 non-null object
status                  2405 non-null object
namjesten               2405 non-null object
balkon                  2405 non-null object
dtypes: float64(2), int64(1), object(11)
memory usage: 263.1+ KB

In [195]:
for i in df['Godina izgradnje']:
    if str(i) == 'nan':
        df.loc[df['Godina izgradnje']== i, 'Godina izgradnje'] = 'no info'

In [198]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2405 entries, 0 to 2404
Data columns (total 14 columns):
url                     2405 non-null object
naziv                   2402 non-null object
cijena                  2405 non-null int64
lokacija                2405 non-null object
lat                     2352 non-null float64
lng                     2352 non-null float64
Kvadrata                2402 non-null object
Broj soba               2402 non-null object
Adresa                  2232 non-null object
Godina izgradnje        1175 non-null object
Primarna orjentacija    1028 non-null object
status                  2405 non-null object
namjesten               2405 non-null object
balkon                  2405 non-null object
dtypes: float64(2), int64(1), object(11)
memory usage: 263.1+ KB

In [246]:
df['dodatna kvadratura'] = 'no info'
for i in df['Kvadrata']:
    if '+' in str(i):
        df.loc[df['Kvadrata'] == i, 'dodatna kvadratura'] = i.split('+')[1]

In [210]:
df[df['dodatna kvadratura']!='no info']

,url,naziv,cijena,lokacija,lat,lng,Kvadrata,Broj soba,Adresa,Godina izgradnje,Primarna orjentacija,status,namjesten,balkon,dodatna kvadratura
188,https://www.olx.ba/artikal/31479861/jednosoban...,JEDNOSOBAN STAN,85000,"Sarajevo, Novi Grad",43.827170,18.348523,36 + 6,Jednosoban (1),M. KAMERIĆA,1980-1989,Istok,nepoznat,nema info,NE,6
320,https://www.olx.ba/artikal/29044527/lux-dom-vi...,LUX DOM / VISNJIK 28m2 +2 m2,70000,Sarajevo - Centar,43.863809,18.416166,28+2,Jednosoban (1),Visnjik,NaN,NaN,nepoznat,nema info,NE,2
402,https://www.olx.ba/artikal/29393650/trosoban-s...,"Trosoban stan Alipašino polje, C faza, Novi grad!",122500,"Sarajevo, Novi Grad",43.841770,18.353193,70 + 3,Trosoban (3),Bosanska,1970-1979,Sjeveroistok,nepoznat,nema info,NE,3
595,https://www.olx.ba/artikal/29773662/bauland-pr...,BAULAND prodaje: Trosoban/Maršala Tita,195000,Sarajevo - Centar,43.858842,18.418934,43 + 21,Trosoban (3),Maršala Tita,NaN,NaN,nepoznat,nema info,NE,21
603,https://www.olx.ba/artikal/26845804/breka-tros...,Breka trosoban stan sa balkonom 80m2,169000,Sarajevo - Centar,43.856259,18.413076,80 + balkon,Trosoban (3),Juraja Najtharta,1980-1989,Sjeveroistok,nepoznat,nema info,DA,balkon
650,https://www.olx.ba/artikal/31200826/cetverosob...,ČETVEROSOBAN STAN VOJNIČKO POLJE 110 m2 10 m2,160000,"Sarajevo, Novi Grad",43.839785,18.341421,110 +10,Četverosoban (4),Teheranski trg,2000-2009,Ostalo,nepoznat,nema info,NE,10
652,https://www.olx.ba/artikal/30691710/troiposoba...,TROIPOSOBAN STAN KOD SCC - a,165000,Sarajevo - Centar,43.856591,18.407873,101 + 24,Četverosoban (4),Kralja Tvrtka,Prije 1950,NaN,nepoznat,nema info,NE,24
653,https://www.olx.ba/artikal/21976793/ciglane-61...,"CIGLANE, 61M2 9m2",123000,Sarajevo - Centar,43.866911,18.407283,61+9,Dvosoban (2),Antuna Hangija,1980-1989,NaN,nepoznat,nema info,NE,9
1023,https://www.olx.ba/artikal/26260487/salonski-s...,Salonski stan u Centru-Marijin Dvor,280000,Sarajevo - Centar,43.856259,18.407755,104+12,Četverosoban (4),Kralja Tvrtka,NaN,Jugozapad,nepoznat,nema info,NE,12
1174,https://www.olx.ba/artikal/30842900/sigenx-pro...,Sigenx prodaje:Dvosoban stan na Grbavici/1.sprat,108000,Novo Sarajevo,43.850501,18.402095,54 +balkon,Dvosoban (2),Splitska,NaN,NaN,nepoznat,nema info,DA,balkon
1196,https://www.olx.ba/artikal/31304719/jednoiposo...,"Jednoiposoban stan Vraca, Novo Sarajevo!",105600,Novo Sarajevo,43.846934,18.397202,48 + 4.5,Jednoiposoban (1.5),Avde Smajlovića,1980-1989,Jugozapad,nepoznat,nema info,NE,4.5
1200,https://www.olx.ba/artikal/29769605/trosoban-s...,"Trosoban, stilski stan - Alipašino polje, Novi...",139000,"Sarajevo, Novi Grad",43.842343,18.353655,78 + 2 + 3,Trosoban (3),Bosanska,1970-1979,Jugozapad,nepoznat,nema info,NE,2
1380,https://www.olx.ba/artikal/28947760/stan-centar/,STAN CENTAR,368500,Sarajevo - Centar,43.860312,18.419707,90+48+16+15,Trosoban (3),Dalmatinska,NaN,Jug,nepoznat,nema info,NE,48
1590,https://www.olx.ba/artikal/30909339/prodajem-s...,Prodajem stan u strogom centru grada!,245000,Sarajevo - Centar,43.860158,18.421659,63 + 4,Dvosoban (2),1970-1979,NaN,Zapad,nepoznat,nema info,NE,4
1679,https://www.olx.ba/artikal/30073225/prodajem-s...,Prodajem stan ili mjenjam za manji,175000,Novo Sarajevo,43.846849,18.377192,86 +10 balkoni,Trosoban (3),Milana Preloga 21,NaN,NaN,nepoznat,nema info,DA,10 balkoni
1712,https://www.olx.ba/artikal/20495663/hrasno-trg...,Hrasno Trg heroja dvosoban stan,120000,Novo Sarajevo,43.848917,18.383079,59+6,Dvosoban (2),Trg heroja,1980-1989,Jugoistok,nepoznat,nema info,NE,6
1979,https://www.olx.ba/artikal/31080794/stan-za-auto/,Stan za auto,124000,"Sarajevo, Novi Grad",43.845071,18.340509,59+10(hobi soba),Dvosoban (2),andreja andrejevića,1980-1989,NaN,nepoznat,nema info,NE,10(hobi soba)
2008,https://www.olx.ba/artikal/31021584/stan-vogosca/,Stan Vogošca,135000,Vogošća,43.902228,18.342587,82+balkon,Trosoban (3),Tome Mendeša,2000-2009,NaN,nepoznat,nema info,DA,balkon
2010,https://www.olx.ba/artikal/29969462/sigenx-pro...,SIGENX prodaje: Stan / Višnjik / Centar / Dere...,60000,Sarajevo - Centar,43.866497,18.420624,29 + 17,Jednosoban (1),Derebent,NaN,NaN,nepoznat,nema info,NE,17
2164,https://www.olx.ba/artikal/25494818/dobrinja-c...,Dobrinja C-5 / 86 m2 / III. sprat / 110.000 KM,110000,"Sarajevo, Novi Grad",43.848427,18.347600,58 + 28,Trosoban (3),Voje Dimitrijevića,NaN,Sjeveroistok,nepoznat,nema info,NE,28
2311,https://www.olx.ba/artikal/30099088/stan-saraj...,Stan Sarajevo Grbavica,139000,Novo Sarajevo,43.849584,18.400672,62 + 2 balkona,Dvosoban (2),Zagrebačka,NaN,NaN,nepoznat,nema info,DA,2 balkona
2393,https://www.olx.ba/artikal/16460713/dvoetazni-...,Dvoetažni stan u Vogošći!,128000,Vogošća,43.903156,18.342373,64 + 64,Petosoban i više,Feriza Merzuka,NaN,NaN,nepoznat,nema info,NE,64

In [209]:
for i in df['dodatna kvadratura']:
    if 'balkon' in str(i):
        df.loc[df['dodatna kvadratura'] == i, 'balkon'] = 'DA'

In [219]:
df[df['cijena']<10000]['Kvadrata']

1             54-118
15            102,46
24             65,85
76                70
87             62,69
88             74,68
89             73,54
94                50
115            32-70
137               72
267            Od 80
318               54
359               57
404              142
419              105
445               64
453            77,67
490            72,94
491            43,18
492            79,18
493            73,71
494            72,96
662               80
664              134
717               72
719               67
745              128
752               76
756               77
757               85
            ...
1438            72.1
1439            76.4
1498              53
1506              81
1507              67
1513          110,46
1532             130
1662              59
1671              40
1674             120
1741           97,31
1744              61
1748           80,02
1947          50, 65
1982          55-114
1985           45,26
1987              56
1997              64
2045    OD 80 DO 137
2059              74
2115           54,31
2254           57.74
2262          75-130
2285             300
2294             122
2295              84
2365           63,98
2366          134,46
2367           89,06
2389          29-180
Name: Kvadrata, Length: 87, dtype: object

In [262]:
df.tail()

,url,naziv,cijena,lokacija,lat,lng,Kvadrata,Broj soba,Adresa,Godina izgradnje,Primarna orjentacija,status,namjesten,balkon,dodatna kvadratura
2394,https://www.olx.ba/artikal/3987548/prodaje-se-...,PRODAJE SE ATRAKTIVAN STAN U SARAJEVU-Ul.Titova,345000,Sarajevo - Centar,43.858916,18.419824,145,Četverosoban (4),Titova,no info,no info,nepoznat,nema info,NE,no info
2395,https://www.olx.ba/artikal/23871104/centar-stan/,Centar stan,249000,Sarajevo - Centar,43.859031,18.420600,101,Četverosoban (4),Dalmatinska,Prije 1950,Sjeveroistok,nepoznat,nema info,NE,no info
2396,https://www.olx.ba/artikal/19872037/sestosoban...,Šestosoban stan na Mejtašu,355000,Stari Grad,43.861239,18.423926,174,Petosoban i više,Mehmed Paše Sokolović,no info,no info,nepoznat,nema info,NE,no info
2397,https://www.olx.ba/artikal/27002548/alipasino-...,ALIPAŠINO POLJE STAN 72m2 ul:Ive Andrića,105000,"Sarajevo, Novi Grad",43.844604,18.347793,72,Trosoban (3),Ive Andrića,no info,no info,nepoznat,nema info,NE,no info
2398,https://www.olx.ba/artikal/25497806/cetverosob...,Četverosoban stan Marijin Dvor,279000,Sarajevo - Centar,43.857891,18.408935,112.83,Četverosoban (4),Kranjčevićeva 7,no info,Jugoistok,nepoznat,nema info,NE,no info

In [227]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2405 entries, 0 to 2404
Data columns (total 15 columns):
url                     2405 non-null object
naziv                   2402 non-null object
cijena                  2405 non-null int64
lokacija                2405 non-null object
lat                     2352 non-null float64
lng                     2352 non-null float64
Kvadrata                2402 non-null object
Broj soba               2402 non-null object
Adresa                  2232 non-null object
Godina izgradnje        1175 non-null object
Primarna orjentacija    1028 non-null object
status                  2405 non-null object
namjesten               2405 non-null object
balkon                  2405 non-null object
dodatna kvadratura      2405 non-null object
dtypes: float64(2), int64(1), object(12)
memory usage: 281.9+ KB

In [248]:
df = pd.read_csv('stanovi_podaci_filtrirani2.csv')

In [240]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2405 entries, 0 to 2404
Data columns (total 15 columns):
url                     2405 non-null object
naziv                   2405 non-null object
cijena                  2405 non-null int64
lokacija                2405 non-null object
lat                     2352 non-null float64
lng                     2352 non-null float64
Kvadrata                2401 non-null object
Broj soba               2402 non-null object
Adresa                  2232 non-null object
Godina izgradnje        2405 non-null object
Primarna orjentacija    2405 non-null object
status                  2405 non-null object
namjesten               2405 non-null object
balkon                  2405 non-null object
dodatna kvadratura      2405 non-null object
dtypes: float64(2), int64(1), object(12)
memory usage: 281.9+ KB

In [243]:
for i in df['Kvadrata']:
    if '-' in str(i):
        print(i)

54-118
32-70
32-110
30 - 135
38 izvorno - 44 nakon adaptacije
55-114
96-100
75-130
53-65
29-180

In [250]:
df['namjesten'].value_counts()

nema info    2349
DA             50
Name: namjesten, dtype: int64

In [254]:
kolone = ['Namjesten?']


linkovi = df['url']
linkovi = pd.DataFrame(linkovi)

In [261]:
features_dict = {}
col = []
val = []
for i in tqdm_notebook(range(len(linkovi))):
    val_turn = []
    resp = requests.get(linkovi['url'][i])
    if str(resp) == '<Response [404]>':
        val.append('NaN')
    
    soup = BeautifulSoup(resp.text, 'html.parser')
    try:
        section1 = soup.find('div', id='dodatnapolja1')

        sections = section1.select('.df')
        for section in sections:
            x = section.select('.df1')[0].text.strip()
            y = section.select('.df2')[0].text.strip()
           
            if x == 'Namješten?':
                col.append(x)
                if y=='':
                    y='NaN'
                val_turn.append(y)            
                  
                
    except:
        val.append('NaN')
        continue
     
    val.append(val_turn)

HBox(children=(IntProgress(value=0, max=2399), HTML(value='')))

In [264]:
val2=[]

for i in val:
    if i == 'NaN':
        val2.append(['NaN'])
    else:
        val2.append(i)

In [265]:
val2 = pd.DataFrame(val2, columns=['Namjesten'])

In [267]:
df = df.join(val2, lsuffix='_df', rsuffix='_df2')

In [268]:
df.head()

,url,naziv,cijena,lokacija,lat,lng,Kvadrata,Broj soba,Adresa,Godina izgradnje,Primarna orjentacija,status,namjesten,balkon,dodatna kvadratura,Namjesten
0,https://www.olx.ba/artikal/31090915/trosoban-s...,"Trosoban stan,82m2 Čengić Vila RENOVIRAN",178900,Novo Sarajevo,43.850312,18.369865,73,Trosoban (3),Džemala Bijedića,1980-1989,no info,nepoznat,nema info,NE,no info,Namješten
1,https://www.olx.ba/artikal/31109536/bauland-pr...,BAULAND prodaje: Trosoban/ Novogradnja/Pejton,163000,Ilidža,43.833914,18.299010,67,Trosoban (3),Prve samostalne brigade,2010+,no info,novogradnja,nema info,NE,no info,Namješten
2,https://www.olx.ba/artikal/29115595/prostor-pr...,PROSTOR prodaje: NOVOGRADNJA trosoban stan sa ...,103350,"Sarajevo, Novi Grad",43.850438,18.356290,53,Trosoban (3),Džemala Bijedića,Novogradnja,Istok,novogradnja,nema info,DA,no info,Nenamješten
3,https://www.olx.ba/artikal/30908536/novogradnj...,"NOVOGRADNJA Skenderija, dvoiposoban 52-53m2 AK...",182385,Sarajevo - Centar,43.852924,18.410201,52,Trosoban (3),Terezija,Novogradnja,no info,novogradnja,nema info,NE,no info,Nenamješten
4,https://www.olx.ba/artikal/30050597/prostor-pr...,"PROSTOR prodaje: NOVOGRADNJA Sarajevo Waves, I...",172422,Ilidža,43.838372,18.297164,62,Dvosoban (2),Barska,Novogradnja,Zapad,novogradnja,nema info,NE,no info,Nenamješten

In [269]:
df.to_csv('noviFeaturi.csv', encoding='utf-8', index=False)